### ISSUE TITLE
Lack some functionalities

### ISSUE THREAD

**Issue by apchee** [szKarlen/atomics.net#5]
Seems it lacks of some functionalities. For example:
AtomicLong counter=new AtomicLong(0,true);

After a while, I want to set it to 50:
counter.Reset(50);   // The value should be 50
counter.Add(-5);     // The value should be 45

Maybe it's just my cases.

Thanks
Dominic

**Comment by szKarlen** [comment]
Hi Dominic,

A reset operation can be achieved by simply calling `AtomicLong.Store()` or assigning a value to `AtomicLong.Value` property.

Although `AtomicLong.Add` might be simulated using [AtomicLong+ operator](https://github.com/szKarlen/atomics.net/blob/master/src/System.Threading.Atomics/AtomicLong.cs#L254) with a subsequent store operation, it won't guarantee (sic!) the same semantics, which `Interlocked.Add` does.
@apchee
